# Generated by Django 3.1.2 on 2020-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='subcateoty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cateory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
    ]
