# Generated by Django 3.1.2 on 2020-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201030_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='subcateoty',
            new_name='subcategory',
        ),
    ]
