# Generated by Django 3.1.2 on 2020-11-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_customer_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Product',
        ),
    ]
