# Generated by Django 3.1.3 on 2020-11-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_orderitemsoup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsoup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.productsoup'),
        ),
    ]
